name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - lifthus
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A bug happened...
    validations:
      required: true
  - type: textarea
    id: what-caused
    attributes:
      label: Why do you think it happened?
      description: Let us know if you have got any idea that comes to mind.
      placeholder: I think it's...
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: v0.0.0
    validations:
      required: false
  - type: dropdown
    id: oss
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - Mac
        - Windows
        - Android
        - IOS
        - etc
  - type: dropdown
    id: browsers
    attributes:
      label: What browser are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - etc
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: 
      options:
        - label: I've checked if there's any other issue about this.
          required: true
